oauth-wg/oauth-v2-1

convert-v2-1.sh
draft-parecki-oauth-v2-1.md

Changes to build --v3 html

---

draft-ietf-oauth-v2-1.md

Uses RFC7235 instead of obsoleted RFC2617

RFC2617 is obsoleted by RFC7235

---

draft-ietf-oauth-v2-1.md

"authorization request" should be "authorization response"

Fix typo in section 9.7

---

draft-ietf-oauth-v2-1.md

- "user agent" is the user agent, "user-agent" is an abnf syntax.
- add reference to notational conventions.

Add user agent to Notational conventions. See #71.

---

draft-ietf-oauth-v2-1.md
oauth-v2-0.md

These are suggested changes for a quite trivial issue. Please, take a look at my explanation in https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/199#issuecomment-782567583 for more details.

Remove the Pragma header.

---

docker/Dockerfile
docker/convert-v2-1.sh
docker/howto.txt
draft-ietf-oauth-v2-1.md

Hi,
I made a first attempt to refactor the draft.
Please give me feedback on the direction.
thanks,
Torsten.

Refactoring (move refresh token into grant section)

---

draft-ietf-oauth-v2-1.md

rewords a circular definition in §2.3

Reword circular definition in Client Authentication. See #71

---

draft-ietf-oauth-v2-1.md

add section mentioning removal of implicit flow

---

draft-ietf-oauth-v2-1.md

Suggested changes for https://github.com/aaronpk/oauth-v2-1/issues/103.

Mnr changes for the abstract

---

draft-ietf-oauth-v2-1.md

Use numbers in the figure as they were also used in the following steps.

Use numbers in the figure instead of characters

---

draft-ietf-oauth-v2-1.md

mention PAR as one option for redirect URI registration at runtime

---

draft-ietf-oauth-v2-1.md

Fixed https://github.com/oauth-wg/oauth-v2-1/issues/144

Fix broken link on Section 4.3.Refresh Token Grant

---

draft-ietf-oauth-v2-1.md

fix https://github.com/oauth-wg/oauth-v2-1/issues/153

Fix clickjacking http message example format

---

draft-ietf-oauth-v2-1.md

cb2616f30c91b68b99f8eb492cce400bf394bc08 - Removes a duplicate "are".

Remove duplicate "are"

---

draft-ietf-oauth-v2-1.md

happy to add anyone else in a single PR to reduce noise

add self to acknowledgements

---

draft-ietf-oauth-v2-1.md

fix: typos

---

draft-ietf-oauth-v2-1.md

expand on reasons why no refresh token expiration is provided

---

draft-ietf-oauth-v2-1.md

add key rotation recommendation for access tokens

---

draft-ietf-oauth-v2-1.md

...in the "phishing attacks" security consideration section
closes #188

add a mention of phishing-resistant authenticators

---

draft-ietf-oauth-v2-1.md

Adds no extra text other than fixes for spellings and removals of extra whitespaces in a few sentences.

Fixes 3 spellings and removes extra whitespaces
